#!/bin/sh

DIR_OUTPUT=$HOME/.bevy
FILE_CONFIG=$HOME/.bevyrc
PALETTE_COLOR_GREEN='\033[0;32m'
PALETTE_COLOR_NONE='\033[0m'

declare -a ARRAY_FILTER_RESULTS_GIT
declare -a ARRAY_FILTER_RESULTS_CURL
#declare -a ARRAY_FILTER_TYPE
#ARRAY_FILTER_TYPE=($(sed -n -e '/^\[/p' $FILE_CONFIG | sed 's/[][]//g'))


util_dir_create() {
  if [ ! -d $1 ]; then
    mkdir -p $1 && echo -e "${PALETTE_COLOR_GREEN}Created Directory: $1${PALETTE_COLOR_NONE}"
  fi
} && util_dir_create $DIR_OUTPUT


util_shell_execute() {
  if [ "$1" = "git" ]; then
    shift
    for i in "$@"; do
      echo git clone "https://github.com/$i.git"
    done
  fi
}


config_array_filter_assign() {
  ARRAY_FILTER_RESULTS_GIT=($(sed -n '/\[git\]/,/^$/{//!p;}' $FILE_CONFIG))
  ARRAY_FILTER_RESULTS_CURL=($(sed -n '/\[curl\]/,/^$/{//!p;}' $FILE_CONFIG))
}


config_parse() {
  if [ -e $FILE_CONFIG ]; then
    while read -r line; do
      #echo $line
    done < $FILE_CONFIG
  fi
}


config_array_filter_assign
util_shell_execute "git" "${ARRAY_FILTER_RESULTS_GIT[@]}"
#config_parse
